//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDeBaile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaseBailarin
    {
        public long idClase { get; set; }
        public long IdBailarin { get; set; }
        public long Id { get; set; }
    
        public virtual Bailarin Bailarin { get; set; }
        public virtual Clase Clase { get; set; }
    }
}
