//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDeBaile
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUsuario1
    {
        public long Id { get; set; }
        public string NombreUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    }
}
