//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDeBaile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademiaDeBaileEntities : DbContext
    {
        public AcademiaDeBaileEntities()
            : base("name=AcademiaDeBaileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bailarin> Bailarin { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<ClaseBailarin> ClaseBailarin { get; set; }
        public virtual DbSet<Instructor> Instructor { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<LoginUsuario1> LoginUsuario1 { get; set; }
    }
}
